# Generated by Django 3.2.9 on 2021-11-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_auto_20211115_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('success', 'Active'), ('info', 'Suspended'), ('red', 'Spam'), ('primary', 'Solved')], max_length=250),
        ),
    ]
